DRS Manifest style changes
Sage-Bionetworks/RECOVER-cohort-builder pull request #1
Opened 2024-02-28 15:47 UTC by itismeghasyam

2024-03-01 23:16 UTC, pranavanba approved these changes
Looks good so far

One thing to keep in mind- when developing for use with production data, reconsider using `dplyr::rowwise()` since it is less efficient than vectorized operations, e.g., `dplyr::rowwise() %>% dplyr::mutate()` will significantly impact performance on large datasets vs using just `dplyr::mutate()`.

2024-03-13 16:34 UTC, pranavanba commented on cohort_builder.R
> +rm(pilot_files_to_remove)
Set `manifest="suppress"` in `syncFromSynapse()` to suppress creating manifest file automatically. See [synapseutils.sync.syncFromSynapse](https://python-docs.synapse.org/reference/synapse_utils/?h=syncfrom#synapseutils.sync.syncFromSynapse) for more details.

2024-03-13 16:35 UTC, pranavanba commented on cohort_builder.R
> +rm(pilot_files_to_remove)
Set `manifest="suppress"` in `syncFromSynapse()` to suppress creating manifest file automatically. See [synapseutils.sync.syncFromSynapse](https://python-docs.synapse.org/reference/synapse_utils/?h=syncfrom#synapseutils.sync.syncFromSynapse) for more details.

2024-03-13 16:35 UTC, pranavanba commented on cohort_builder.R
> +rm(pilot_files_to_remove)
Set `manifest="suppress"` in `syncFromSynapse()` to suppress creating manifest file automatically. See [synapseutils.sync.syncFromSynapse](https://python-docs.synapse.org/reference/synapse_utils/?h=syncfrom#synapseutils.sync.syncFromSynapse) for more details.

2024-03-13 16:37 UTC, pranavanba commented on cohort_builder.R
> +aa <- lapply(all_parquet, function(parquet.df){
`aa` could have a more informative name like `parquet_with_participantId` above. Making variable names more descriptive improves code readability.

2024-03-13 16:39 UTC, pranavanba requested changes
See comments above

2024-04-10 20:17 UTC, closed without merging

2024-04-10 20:17 UTC, itismeghasyam commented on cohort_builder.R
> +rm(pilot_files_to_remove)
This function does not exist for synapserutils (R version)